export const ammo = [
  { name: '.38', rarity: 0, source: 'Core, 91' },                 // 39
  { name: '10mm', rarity: 0, source: 'Core, 91' },                // 37
  { name: '.308', rarity: 1, source: 'Core, 91' },                // 17
  { name: 'Flare', rarity: 1, source: 'Core, 91' },               // 18
  { name: 'Shotgun Shell', rarity: 1, source: 'Core, 91' },       // 31
  { name: '.45', rarity: 2, source: 'Core, 91' },                 // 33
  { name: 'Flamer Fuel', rarity: 2, source: 'Core, 91' },
  { name: 'Fusion Cell', rarity: 2, source: 'Core, 91' },
  { name: 'Gamma Round', rarity: 2, source: 'Core, 91' },
  { name: 'Railway Spike', rarity: 2, source: 'Core, 91' },
  { name: 'Syringer Ammo', rarity: 2, source: 'Core, 91' },
  { name: '.44 Magnum', rarity: 3, source: 'Core, 91' },
  { name: '.50', rarity: 3, source: 'Core, 91' },
  { name: '5.56', rarity: 3, source: 'Core, 91' },
  { name: '5mm', rarity: 3, source: 'Core, 91' },
  { name: 'Fusion Core', rarity: 3, source: 'Core, 91' },
  { name: 'Missile', rarity: 3, source: 'Core, 91' },
  { name: 'Plasma Cartridge', rarity: 4, source: 'Core, 91' },
  { name: '2mm EC', rarity: 5, source: 'Core, 91' },
  { name: 'Mini-Nuke', rarity: 6, source: 'Core, 91' },
  { name: '40mm Grenade Round', rarity: 4, source: 'Settlers, 89' },
  { name: 'Acid Concentrate', rarity: 3, source: 'Settlers, 89' },
  { name: 'Alien Blaster Round', rarity: 6, source: 'Settlers, 89' },
  { name: 'Cannonball', rarity: 5, source: 'Settlers, 89' },
  { name: 'Cryo Cell', rarity: 5, source: 'Settlers, 89' },
  { name: 'Gas Grenade', rarity: 4, source: 'Settlers, 89' },
  { name: 'Harpoon', rarity: 4, source: 'Settlers, 89' },
  { name: '.357 Magnum', rarity: 1, source: 'Wanderers, 57' },
  { name: '12.7mm', rarity: 2, source: 'Wanderers, 57' },
  { name: '.50 Ball', rarity: 0, source: 'Wanderers, 57' },
  { name: '25mm Grenade', rarity: 4, source: 'Wanderers, 57' },
  { name: 'Alien Power Cells', rarity: 5, source: 'Wanderers, 57' },
  { name: 'Alien Power Module', rarity: 6, source: 'Wanderers, 57' },
  { name: 'Arrow', rarity: 1, source: 'Wanderers, 57' },
  { name: 'Crossbow Bolt', rarity: 2, source: 'Wanderers, 57' },
  { name: 'Plasma Core', rarity: 6, source: 'Wanderers, 57' },
];
export const smallGuns = [
  { name: '.44 Pistol', rarity: 2, source: 'Core, 95' },
  { name: '10mm Pistol', rarity: 1, source: 'Core, 95' },
  { name: '10mm Auto Pistol (Automatic Receiver)', rarity: 2, source: 'Core, 95' },
  { name: 'Flare Gun', rarity: 1, source: 'Core, 95' },
  { name: 'Assault Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Combat Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Gauss Rifle', rarity: 4, source: 'Core, 95' },
  { name: 'Hunting Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Scoped Hunting Rifle (Long Barrel, Short Scope)', rarity: 3, source: 'Core, 95' },
  { name: 'Submachine Gun', rarity: 1, source: 'Core, 95' },
  { name: 'Combat Shotgun', rarity: 2, source: 'Core, 95' },
  { name: 'Double-Barrel Shotgun', rarity: 1, source: 'Core, 95' },
  { name: 'Pipe Bolt-Action', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Bolt-Action Rifle (Long Barrel, Standard Stock)', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Gun', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Rifle (Long Barrel, Standard Stock)', rarity: 0, source: 'Core, 95' },
  { name: 'Auto Pipe Gun (Automatic Receiver)', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Revolver', rarity: 0, source: 'Core, 95' },
  { name: 'Railway Rifle', rarity: 4, source: 'Core, 95' },
  { name: 'Syringer', rarity: 2, source: 'Core, 95' },
  { name: 'M79 Grenade Launcher', rarity: 3, source: 'Settlers, 90' },
  { name: '.357 Magnum Revolver', rarity: 2, source: 'Wanderers, 60' },
  { name: '12.7mm Pistol', rarity: 4, source: 'Wanderers, 60' },
  { name: '12.7mm SMG', rarity: 4, source: 'Wanderers, 60' },
  { name: '25mm Grenade APW', rarity: 4, source: 'Wanderers, 60' },
  { name: '9mm Pistol', rarity: 2, source: 'Wanderers, 60' },
  { name: 'Anti-Materiel Rifle', rarity: 4, source: 'Wanderers, 60' },
  { name: 'Battle Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Blunderbuss', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Pistol', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Gauss Pistol', rarity: 5, source: 'Wanderers, 60' },
  { name: 'Gauss Shotgun', rarity: 5, source: 'Wanderers, 60' },
  { name: 'Lever-Action Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Light Machine Gun', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Pump-Action Shotgun', rarity: 1, source: 'Wanderers, 60' },
  { name: 'Radium Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Sniper Rifle', rarity: 4, source: 'Wanderers, 60' },
];
export const energyWeapons = [
  { name: 'Institute Laser', rarity: 2, source: 'Core, 101' },
  { name: 'Institute Rifle (Long Barrel, Standard Stock)', rarity: 2, source: 'Core, 101' },
  { name: 'Laser Musket', rarity: 1, source: 'Core, 101' },
  { name: 'Laser Gun', rarity: 2, source: 'Core, 101' },
  { name: 'Laser Rifle (Long Barrel, Standard Stock)', rarity: 2, source: 'Core, 101' },
  { name: 'Plasma Gun', rarity: 3, source: 'Core, 101' },
  { name: 'Plasma Rifle (Long Barrel, Standard Stock)', rarity: 3, source: 'Core, 101' },
  { name: 'Gamma Gun', rarity: 5, source: 'Core, 101' },
  { name: 'Acid Soaker', rarity: 3, source: 'Settlers, 91' },
  { name: 'Alien Blaster', rarity: 5, source: 'Settlers, 91' },
  // { name: 'Assaultron Head Laser', rarity: 4, source: 'Settlers, 91' },
  { name: 'Assaultron Head', rarity: 3, source: 'Wanderers, 65' },
  { name: 'Mesmetron', rarity: 4, source: 'Settlers, 91' },
  { name: 'Alien Atomizer', rarity: 5, source: 'Wanderers, 65' },
  { name: 'Alien Disintegrator', rarity: 5, source: 'Wanderers, 65' },
  { name: 'Arc Welder', rarity: 4, source: 'Wanderers, 65' },
  { name: 'Microwave Emitter', rarity: 5, source: 'Wanderers, 65' },
  // { name: 'Tesla Rifle', rarity: 4, source: 'Settlers, 91' },
  { name: 'Tesla Rifle', rarity: 4, source: 'Wanderers, 65' },
  // Homebrew
  {
    name: "Enclave Plasma Gun", 
    rarity: 4, 
    source: "Homebrew", 
    type: "Energy Weapons", 
    damage: 7, 
    effects: [], 
    damageType: "Physical/Energy", 
    fireRate: 1, 
    range: 'C', 
    qualities: ['Close Quarters'], 
    weight: 4, 
    cost: 246, 
    ammo: 'Plasma Cartridge', 
    description: "A specialized model of plasma gun developed by the Enclave. It has more precise and sophisticated construction than a run-of-the-mill plasma gun, giving it more damage potential but also it's more difficult to modify. Visibly, an Enclave plasma gun is distinguished by its darker color scheme. Any attempt to modify an Enclave plasma gun has +2 complication range. Mods for an Enclave plasma gun are incompatible with a standard plasma gun and vice versa.", 
    modOptions: {
      Capacitor: ["Photon Exciter", "Beta Wave Tuner", "Boosted Capacitor", "Photon Agitator"],
      Barrel: ["Splitter", "Automatic Barrel", "Sniper Barrel", "Flamer Barrel", "Improved Barrel"],
      Grip: ["Sharpshooter's Girp"],
      Stock: ["Standard Stock", "Marksman's Stock", "Recoil-Compensating Stock"],
      Sights: ["Reflex Sight", "Short Scope", "Long Scope", "Short Night Vision Scope", "Long Night Vision Scope", "Recon Scope"]
    }
  }
];
export const bigGuns = [
  { name: 'Fat Man', rarity: 4, source: 'Core, 106' },
  { name: 'Flamer', rarity: 3, source: 'Core, 106' },
  { name: 'Gatling Laser', rarity: 3, source: 'Core, 106' },
  { name: 'Heavy Incinerator', rarity: 4, source: 'Core, 106' },
  { name: 'Junk Jet', rarity: 3, source: 'Core, 106' },
  { name: 'Minigun', rarity: 2, source: 'Core, 106' },
  { name: 'Missile Launcher', rarity: 4, source: 'Core, 106' },
  { name: 'Broadsider', rarity: 5, source: 'Settlers, 94' },
  { name: 'Cryolator', rarity: 4, source: 'Settlers, 94' },
  { name: 'Harpoon Gun', rarity: 5, source: 'Settlers, 94' },
  { name: '.50 Cal Machine Gun', rarity: 3, source: 'Wanderers, 67' },
  { name: 'Auto Grenade Launcher', rarity: 4, source: 'Wanderers, 67' },
  { name: 'Drone Cannon', rarity: 5, source: 'Wanderers, 67' },
  { name: 'Gatling Gun', rarity: 1, source: 'Wanderers, 67' },
  { name: 'Gatling Plasma', rarity: 4, source: 'Wanderers, 67' },
  { name: 'Gauss Minigun', rarity: 6, source: 'Wanderers, 67' },
  { name: 'Plasma Caster', rarity: 5, source: 'Wanderers, 67' },
  { name: 'Tesla Cannon', rarity: 5, source: 'Wanderers, 67' },
];
export const rangedWeapons = [ 
  ...smallGuns, ...energyWeapons, ...bigGuns,
  { name: 'Bow', rarity: 1, source: 'Wanderers, 73' },
  { name: 'Crossbow', rarity: 2, source: 'Wanderers, 73' },
];
export const meleeWeapons = [
  { name: 'Sword', rarity: 2, source: 'Core, 111' },
  { name: 'Combat Knife', rarity: 1, source: 'Core, 111' },
  { name: 'Machete', rarity: 1, source: 'Core, 111' },
  { name: 'Ripper', rarity: 2, source: 'Core, 111' },
  { name: 'Shishkebab', rarity: 3, source: 'Core, 111' },
  { name: 'Switchblade', rarity: 0, source: 'Core, 111' },
  { name: 'Baseball Bat', rarity: 1, source: 'Core, 111' },
  { name: 'Aluminum Baseball Bat', rarity: 2, source: 'Core, 111' },
  { name: 'Board', rarity: 0, source: 'Core, 111' },
  { name: 'Lead Pipe', rarity: 0, source: 'Core, 111' },
  { name: 'Pipe Wrench', rarity: 1, source: 'Core, 111' },
  { name: 'Pool Cue', rarity: 0, source: 'Core, 111' },
  { name: 'Rolling Pin', rarity: 0, source: 'Core, 111' },
  { name: 'Baton', rarity: 1, source: 'Core, 111' },
  { name: 'Sledgehammer', rarity: 2, source: 'Core, 111' },
  { name: 'Super Sledge', rarity: 3, source: 'Core, 111' },
  { name: 'Tire Iron', rarity: 1, source: 'Core, 111' },
  { name: 'Walking Cane', rarity: 0, source: 'Core, 111' },
  { name: 'Boxing Glove', rarity: 1, source: 'Core, 111' },
  { name: 'Deathclaw Gauntlet', rarity: 3, source: 'Core, 111' },
  { name: 'Knuckles', rarity: 1, source: 'Core, 111' },
  { name: 'Power Fist', rarity: 2, source: 'Core, 111' },
  { name: 'Assaultron Blade', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Auto-Axe', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Ballistic Fist', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Bumper Sword', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Cattle Prod', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Chainsaw', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Death Tambo', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Displacer Glove', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Guitar Sword', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Mr Handy Buzz Blade', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Multi-Purpose Axe', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Proton Axe', rarity: 5, source: 'Wanderers, 75' },
  { name: 'War Drum', rarity: 3, source: 'Wanderers, 75' },
];
export const explosives = [
  { name: 'Throwing Knives', rarity: 1, source: 'Core, 119' },
  { name: 'Tomahawk', rarity: 2, source: 'Core, 119' },
  { name: 'Javelin', rarity: 1, source: 'Core, 119' },
  { name: 'Baseball Grenade', rarity: 1, source: 'Core, 120' },
  { name: 'Frag Grenade', rarity: 2, source: 'Core, 120' },
  { name: 'Molotov Cocktail', rarity: 1, source: 'Core, 120' },
  { name: 'Nuka Grenade', rarity: 4, source: 'Core, 120' },
  { name: 'Plasma Grenade', rarity: 3, source: 'Core, 120' },
  { name: 'Pulse Grenade', rarity: 3, source: 'Core, 120' },
  { name: 'Bottlecap Mine', rarity: 2, source: 'Core, 120' },
  { name: 'Frag Mine', rarity: 2, source: 'Core, 120' },
  { name: 'Nuka Mine', rarity: 4, source: 'Core, 120' },
  { name: 'Plasma Mine', rarity: 3, source: 'Core, 120' },
  { name: 'Pulse Mine', rarity: 3, source: 'Core, 120' },
  { name: 'Cryogenic Grenade', rarity: 3, source: 'Wanderers, 79' },
  { name: 'Cryo Mine', rarity: 3, source: 'Wanderers, 79' },
  { name: 'Detonator', rarity: 3, source: 'Wanderers, 79' },
  { name: 'Dynamite', rarity: 2, source: 'Wanderers, 79' },
  { name: 'Dynamite Bundle', rarity: 3, source: 'Wanderers, 79' },
  { name: 'Flash Bang', rarity: 2, source: 'Wanderers, 79' },
  { name: 'Frag Grenade MIRV', rarity: 4, source: 'Wanderers, 79' },
  { name: 'Plastic Explosive', rarity: 4, source: 'Wanderers, 79' },
  { name: 'Powder Charge', rarity: 1, source: 'Wanderers, 79' },
  { name: 'Smoke Grenade', rarity: 2, source: 'Wanderers, 79' },
];
export const clothing = [
  // clothing
  { name: 'Brotherhood of Steel Uniform', rarity: 2, source: 'Core, 124' },
  { name: 'Casual Clothing', rarity: 1, source: 'Core, 124' },
  { name: 'Harness', rarity: 0, source: 'Core, 124' },
  { name: 'Military Fatigues', rarity: 1, source: 'Core, 124' },
  { name: 'Road Leathers', rarity: 1, source: 'Core, 124' },
  { name: 'Tough Clothing', rarity: 1, source: 'Core, 124' },
  { name: 'Vault Jumpsuit', rarity: 2, source: 'Core, 124' },
  { name: 'Marine Wetsuit', rarity: 3, source: 'Wanderers, 85' },
  { name: 'Underarmor Suit', rarity: 2, source: 'Wanderers, 85' },
  // outfits
  { name: 'Brotherhood of Steel Fatigues', rarity: 3, source: 'Core, 124' },
  { name: 'Brotherhood Scribe\'s Armor', rarity: 2, source: 'Core, 124' },
  { name: 'Cage Armor', rarity: 3, source: 'Core, 124' },
  { name: 'Drifter Outfit', rarity: 1, source: 'Core, 124' },
  { name: 'Engineer\'s Armor', rarity: 1, source: 'Core, 124' },
  { name: 'Formal Clothing', rarity: 2, source: 'Core, 124' },
  { name: 'Hazmat Suit', rarity: 3, source: 'Core, 124' },
  { name: 'Heavy Coat', rarity: 1, source: 'Core, 124' },
  { name: 'Hides', rarity: 0, source: 'Core, 124' },
  { name: 'Lab Coat', rarity: 1, source: 'Core, 124' },
  { name: 'Spike Armor', rarity: 2, source: 'Core, 124' },
  { name: 'Utility Coveralls', rarity: 1, source: 'Core, 124' },
  { name: 'Brotherhood Armored Battlecoat', rarity: 4, source: 'Wanderers, 85' },
  { name: 'Brotherhood Bomber Jacket', rarity: 3, source: 'Wanderers, 85' },
  { name: 'Cleanroom Suit', rarity: 2, source: 'Wanderers, 85' },
  { name: 'Hunter\'s Pelt Coat', rarity: 2, source: 'Wanderers, 85' },
  { name: 'Spacesuit Costume', rarity: 4, source: 'Wanderers, 85' },
  // hats
  { name: 'Army Helmet', rarity: 1, source: 'Core, 124' },
  { name: 'Brotherhood of Steel Hood', rarity: 2, source: 'Core, 124' },
  { name: 'Brotherhood Scribe\'s Hat', rarity: 2, source: 'Core, 124' },
  { name: 'Casual Hat', rarity: 1, source: 'Core, 124' },
  { name: 'Formal Hat', rarity: 2, source: 'Core, 125' },
  { name: 'Gas Mask', rarity: 2, source: 'Core, 125' },
  { name: 'Hard Hat', rarity: 1, source: 'Core, 125' },
  { name: 'Hood/Cowl', rarity: 1, source: 'Core, 125' },
  { name: 'Sack Hood', rarity: 0, source: 'Core, 125' },
  { name: 'Welder\'s Visor', rarity: 2, source: 'Core, 125' },
  { name: 'Beer Hat', rarity: 2, source: 'Wanderers, 85' },
  { name: 'Marine Tactical Helmet', rarity: 3, source: 'Wanderers, 85' },
  { name: 'Spacesuit Helmet', rarity: 5, source: 'Wanderers, 85' },
  { name: 'Hunter\'s Hood', rarity: 2, source: 'Wanderers, 85' },
];
export const armor = [
  // dog
  { name: 'Dog Helmet', rarity: 2, source: 'Core, 123' },
  { name: 'Dog Armor (Light)', rarity: 1, source: 'Core, 123' },
  { name: 'Dog Armor (Medium)', rarity: 2, source: 'Core, 123' },
  { name: 'Dog Armor (Heavy)', rarity: 3, source: 'Core, 123' },
  // armor pieces
  { name: 'Raider Armor Piece (Standard)', rarity: 0, source: 'Core, 130' },
  { name: 'Raider Armor Piece (Sturdy)', rarity: 1, source: 'Core, 130' },
  { name: 'Raider Armor Piece (Heavy)', rarity: 2, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Standard)', rarity: 1, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Sturdy)', rarity: 2, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Heavy)', rarity: 3, source: 'Core, 130' },
  { name: 'Metal Armor Piece (Standard)', rarity: 1, source: 'Core, 131' },
  { name: 'Metal Armor Piece (Sturdy)', rarity: 2, source: 'Core, 131' },
  { name: 'Metal Armor Piece (Heavy)', rarity: 3, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Standard)', rarity: 2, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Sturdy)', rarity: 3, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Heavy)', rarity: 4, source: 'Core, 131' },
  { name: 'Synth Armor Piece (Standard)', rarity: 3, source: 'Core, 132' },
  { name: 'Synth Armor Piece (Sturdy)', rarity: 4, source: 'Core, 132' },
  { name: 'Synth Armor Piece (Heavy)', rarity: 5, source: 'Core, 132' },
  { name: 'Vault-Tec Security Helmet', rarity: 1, source: 'Core, 132' },
  { name: 'Vault-Tec Security Armor', rarity: 1, source: 'Core, 132' },
  { name: 'Legionary Armor Piece (Recruit)', rarity: 3, source: 'Wanderers, 89' },
  { name: 'Legionary Armor Piece', rarity: 4, source: 'Wanderers, 89' },
  { name: 'Legionary Armor Piece (Centurion)', rarity: 5, source: 'Wanderers, 89' },
  { name: 'Marine Armor Piece', rarity: 4, source: 'Wanderers, 90' },
  { name: 'Scout Armor Piece', rarity: 4, source: 'Wanderers, 91' },
  { name: 'Robot Armor Piece (Standard)', rarity: 2, source: 'Wanderers, 92' },
  { name: 'Robot Armor Piece (Sturdy)', rarity: 3, source: 'Wanderers, 92' },
  { name: 'Robot Armor Piece (Heavy)', rarity: 4, source: 'Wanderers, 92' },
  { name: 'Wood Armor Piece', rarity: 0, source: 'Wanderers, 93' },
  // Power Armor
  { name: 'Power Armor Frame', rarity: 4, source: 'Core, 137' },
  { name: 'Raider Power Armor Piece', rarity: 2, source: 'Core, 137' },
  { name: 'T-45 Power Armor Piece', rarity: 2, source: 'Core, 137' },
  { name: 'T-51 Power Armor Piece', rarity: 3, source: 'Core, 137' },
  { name: 'T-60 Power Armor Piece', rarity: 4, source: 'Core, 137' },
  { name: 'X-01 Power Armor Piece', rarity: 5, source: 'Core, 137' },
  { name: 'Excavator Power Armor Piece', rarity: 3, source: 'Wanderers, 94' },
  { name: 'Hellcat Power Armor Piece', rarity: 3, source: 'Wanderers, 95' },
  { name: 'T-65 Power Armor Piece', rarity: 6, source: 'Wanderers, 89' },
  // whole armor
  { name: 'Chinese Stealth Armor', rarity: 6, source: 'Wanderers, 88' },
  { name: 'Diving Suit', rarity: 3, source: 'Wanderers, 88' },
  { name: 'Recon Armor', rarity: 4, source: 'Wanderers, 91' },
];
export const rawMeat = [
  { name: 'Bloatfly Meat', rarity: 0, source: 'Core, 149' },
  { name: 'Bloodbug Meat', rarity: 1, source: 'Core, 149' },
  { name: 'Brahmin Meat', rarity: 1, source: 'Core, 149' },
  { name: 'Deathclaw Egg', rarity: 3, source: 'Core, 149' },
  { name: 'Deathclaw Meat', rarity: 3, source: 'Core, 149' },
  { name: 'Iguana Bits', rarity: 1, source: 'Core, 150' },
  { name: 'Mirelurk Egg', rarity: 2, source: 'Core, 150' },
  { name: 'Mirlurk Meat', rarity: 1, source: 'Core, 150' },
  { name: 'Mole Rat Meat', rarity: 0, source: 'Core, 150' },
  { name: 'Mongrel Dog Meat', rarity: 0, source: 'Core, 150' },
  { name: 'Mutant Hound Meat', rarity: 2, source: 'Core, 150' },
  { name: 'Queen Mirelurk Meat', rarity: 4, source: 'Core, 151' },
  { name: 'Radroach Meat', rarity: 0, source: 'Core, 151' },
  { name: 'Radscorpion Egg', rarity: 3, source: 'Core, 151' },
  { name: 'Radscorpion Meat', rarity: 2, source: 'Core, 151' },
  { name: 'Radstag Meat', rarity: 1, source: 'Core, 151' },
  { name: 'Softshell Mirelurk Meat', rarity: 2, source: 'Core, 151' },
  { name: 'Squirrel Bits', rarity: 1, source: 'Core, 151' },
  { name: 'Stingwing Meat', rarity: 1, source: 'Core, 151' },
  { name: 'Yao Guai Meat', rarity: 3, source: 'Core, 151' },
  { name: 'Angler Meat', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Cave Cricket Meat', rarity: 1, source: 'Wanderers, 114' },
  { name: 'Cazador Egg', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Gecko Meat', rarity: 1, source: 'Wanderers, 114' },
  { name: 'Giant Ant Meat', rarity: 0, source: 'Wanderers, 114' },
  { name: 'Giant Mantis Foreleg', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Gulper Innards', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Hermit Crab Meat', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Mega Sloth Meat', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Mega Sloth Mushroom', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Radrat Meat', rarity: 0, source: 'Wanderers, 115' },
  { name: 'Scorchbeast Meat', rarity: 4, source: 'Wanderers, 115' },
  { name: 'Sheepsquatch Meat', rarity: 4, source: 'Wanderers, 115' },
  { name: 'Snallygaster Innards', rarity: 3, source: 'Wanderers, 115' },
];
export const cookedMeals = [
  { name: 'Baked Bloatfly', rarity: 1, source: 'Core, 149' },
  { name: 'Bloodbug Steak', rarity: 2, source: 'Core, 149' },
  { name: 'Cooked Softshell Meat', rarity: 3, source: 'Core, 149' },
  { name: 'Crispy Squirrel Bits', rarity: 2, source: 'Core, 149' },
  { name: 'Deathclaw Omelette', rarity: 4, source: 'Core, 150' },
  { name: 'Deathclaw Steak', rarity: 4, source: 'Core, 150' },
  { name: 'Grilled Radroach', rarity: 1, source: 'Core, 150' },
  { name: 'Grilled Radstag', rarity: 2, source: 'Core, 150' },
  { name: 'Iguana on a Stick', rarity: 2, source: 'Core, 150' },
  { name: 'Iguana Soup', rarity: 3, source: 'Core, 150' },
  { name: 'Mirelurk Cake', rarity: 3, source: 'Core, 150' },
  { name: 'Mirelurk Egg Omelette', rarity: 3, source: 'Core, 150' },
  { name: 'Mirelurk Queen Steak', rarity: 5, source: 'Core, 150' },
  { name: 'Mole Rat Chunks', rarity: 1, source: 'Core, 150' },
  { name: 'Mutant Hound Chops', rarity: 3, source: 'Core, 150' },
  { name: 'Mutt Chops', rarity: 1, source: 'Core, 150' },
  { name: 'Noodle Cup', rarity: 2, source: 'Core, 150' },
  { name: 'Potted Meat', rarity: 0, source: 'Core, 151' },
  { name: 'Radscorpion Egg Omelette', rarity: 4, source: 'Core, 151' },
  { name: 'Radscorpion Steak', rarity: 3, source: 'Core, 151' },
  { name: 'Radstag Stew', rarity: 3, source: 'Core, 151' },
  { name: 'Ribeye Steak', rarity: 2, source: 'Core, 151' },
  { name: 'Roasted Mirelurk Meat', rarity: 2, source: 'Core, 151' },
  { name: 'Squirrel on a Stick', rarity: 2, source: 'Core, 151' },
  { name: 'Squirrel Stew', rarity: 2, source: 'Core, 151' },
  { name: 'Stingwing Filet', rarity: 2, source: 'Core, 151' },
  { name: 'Vegetable Soup', rarity: 2, source: 'Core, 151' },
  { name: 'Yao Guai Ribs', rarity: 4, source: 'Core, 151' },
  { name: 'Yao Guai Roast', rarity: 4, source: 'Core, 151' },
  { name: 'Cazador Omelet', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Crispy Cave Cricket', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Gecko Kebab', rarity: 1, source: 'Wanderers, 114' },
  { name: 'Grilled Giant Mantis', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Gulper Slurry', rarity: 2, source: 'Wanderers, 114' },
  { name: 'Hermit Crab Steak', rarity: 4, source: 'Wanderers, 114' },
  { name: 'Honey Cake', rarity: 4, source: 'Wanderers, 114' },
  { name: 'Lamb Chops', rarity: 4, source: 'Wanderers, 114' },
  { name: 'Mega Sloth Steak', rarity: 4, source: 'Wanderers, 114' },
  { name: 'Mega Sloth Mushroom Soup', rarity: 3, source: 'Wanderers, 115' },
  { name: 'Mongrel Ribs', rarity: 2, source: 'Wanderers, 115' },
  { name: 'Mutton Meat Pie', rarity: 4, source: 'Wanderers, 115' },
  { name: 'Poached Angler', rarity: 4, source: 'Wanderers, 115' },
  { name: 'Roasted Radrat', rarity: 1, source: 'Wanderers, 115' },
  { name: 'Scorchbeast Steak', rarity: 4, source: 'Wanderers, 115' },
  { name: 'Snallygaster Stew', rarity: 4, source: 'Wanderers, 115' },
];
export const food = [
  // Plant
  { name: 'Brain Fungus', rarity: 1, source: 'Core, 149' },
  { name: 'Carrot', rarity: 1, source: 'Core, 149' },
  { name: 'Carrot (non-irradiated)', rarity: 3, source: 'Core, 149' },
  { name: 'Corn', rarity: 1, source: 'Core, 149' },
  { name: 'Corn (non-irradiated)', rarity: 3, source: 'Core, 149' },
  { name: 'Gourd', rarity: 1, source: 'Core, 150' },
  { name: 'Melon', rarity: 1, source: 'Core, 150' },
  { name: 'Melon (non-irradiated)', rarity: 3, source: 'Core, 150' },
  { name: 'Mutfruit', rarity: 0, source: 'Core, 150' },
  { name: 'Mutfruit (non-irradiated)', rarity: 2, source: 'Core, 150' },
  { name: 'Razorgrain', rarity: 1, source: 'Core, 151' },
  { name: 'Silt Bean', rarity: 1, source: 'Core, 151' },
  { name: 'Tarberry', rarity: 3, source: 'Core, 151' },
  { name: 'Tato', rarity: 1, source: 'Core, 151' },
  { name: 'Honey', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Honeycomb', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Lure Weed', rarity: 1, source: 'Wanderers, 114' },
  // Pre-war
  { name: 'BlamCo Brand Mac and Cheese', rarity: 1, source: 'Core, 149' },
  { name: 'BlamCo Brand Mac and Cheese (preserved)', rarity: 3, source: 'Core, 149' },
  { name: 'Canned Dog Food', rarity: 0, source: 'Core, 149' },
  { name: 'Cram', rarity: 1, source: 'Core, 149' },
  { name: 'Dandy Boy Apples', rarity: 0, source: 'Core, 149' },
  { name: 'Fancy Lad Snack Cakes', rarity: 0, source: 'Core, 150' },
  { name: 'Fancy Lad Snack Cakes (preserved)', rarity: 2, source: 'Core, 150' },
  { name: 'Food Paste', rarity: 2, source: 'Core, 150' },
  { name: 'Gum Drops', rarity: 0, source: 'Core, 150' },
  { name: 'InstaMash', rarity: 0, source: 'Core, 150' },
  { name: 'InstaMash (preserved)', rarity: 2, source: 'Core, 150' },
  { name: 'Institute Food Packet', rarity: 2, source: 'Core, 150' },
  { name: 'Perfectly Preserved Pie', rarity: 3, source: 'Core, 150' },
  { name: 'Pork `n` Beans', rarity: 0, source: 'Core, 150' },
  { name: 'Potato Crisps', rarity: 0, source: 'Core, 150' },
  { name: 'Salisbury Steak', rarity: 0, source: 'Core, 151' },
  { name: 'Salisbury Steak (preserved)', rarity: 2, source: 'Core, 151' },
  { name: 'Sugar Bombs', rarity: 0, source: 'Core, 151' },
  { name: 'Sugar Bombs (preserved)', rarity: 2, source: 'Core, 151' },
  { name: 'Sweet Roll', rarity: 1, source: 'Core, 151' },
  { name: 'Yum-Yum Deviled Eggs', rarity: 0, source: 'Core, 151' },
];
export const beverages = [
  { name: 'Beer', rarity: 1, source: 'Core, 160' },
  { name: 'Blood Pack', rarity: 2, source: 'Core, 160' },
  { name: 'Bourbon', rarity: 2, source: 'Core, 160' },
  { name: 'Brahmin Milk', rarity: 2, source: 'Core, 160' },
  { name: 'Dirty Wastelander', rarity: 3, source: 'Core, 160' },
  { name: 'Dirty Water', rarity: 0, source: 'Core, 160' },
  { name: 'Glowing Blood Pack', rarity: 3, source: 'Core, 160' },
  { name: 'Irradiated Blood', rarity: 2, source: 'Core, 160' },
  { name: 'Melon Juice', rarity: 2, source: 'Core, 160' },
  { name: 'Moonshine', rarity: 2, source: 'Core, 160' },
  { name: 'Mutfruit Juice', rarity: 2, source: 'Core, 160' },
  { name: 'Nuka-Cherry', rarity: 3, source: 'Core, 160' },
  { name: 'Nuka-Cola', rarity: 2, source: 'Core, 160' },
  { name: 'Nuka-Cola Quantum', rarity: 5, source: 'Core, 160' },
  { name: 'Purified Water', rarity: 1, source: 'Core, 160' },
  { name: 'Refreshing Beverage', rarity: 5, source: 'Core, 160' },
  { name: 'Rum', rarity: 2, source: 'Core, 160' },
  { name: 'Tarberry Juice', rarity: 4, source: 'Core, 160' },
  { name: 'Tato Juice', rarity: 3, source: 'Core, 161' },
  { name: 'Vodka', rarity: 3, source: 'Core, 161' },
  { name: 'Whiskey', rarity: 3, source: 'Core, 161' },
  { name: 'Wine', rarity: 3, source: 'Core, 161' },
  // Homebrew
  {
    name: "Nuka-Cola Cranberry",
    rarity: 5,
    source: "Homebrew",
    type: "Beverages",
    hpHealed: 2,
    otherEffects: "Increase one skill by 1 for the remainder of the scene.",
    irradiated: 1,
    weight: 1,
    cost: 30,
    description: "A flavored variant of Nuka-Cola using cranberries from Appalachia. The bright flavor makes you feel a bit sharper. Upon drinking Nuka-Cola Cranberry, choose a skill: that skill is considered 1 point higher for the rest of the day."
  },
  {
    name: "Nuka-Cola Dark", 
    rarity: 5, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 0,
    otherEffects: "Alcoholic. Reroll 1d20 on all STR and END tests.",
    irradiated: '-',
    weight: 1,
    cost: 35,
    description: "A variant made for adult demographics, Nuka-Cola Dark is a pre-mixed Nuka-Cola and Rum. APV is 35%."
  },
  { 
    name: "Nuka-Grape", 
    rarity: 5, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 7,
    otherEffects: "Heal 10 Rad damage. Gain 3 AP.",
    irradiated: '-',
    weight: 1,
    cost: 50,
    description: "Originally sold overseas as Grape-Pearl Soda, it was rebranded as Nuka-Grape after the Nuka-Cola Corporation acquired the recipe. Unrealized before the war, the unique additives used to produce the grape flavor counteract the effects of radiation sickness."
  },
  { 
    name: "Nuka-Cola Orange", 
    rarity: 5, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 7,
    otherEffects: "+1 Rad DR. Gain 3 AP.",
    irradiated: '-',
    weight: 1,
    cost: 50,
    description: "Another fruit-flavored variant, the artificial flavors used included trace quantities of arsenic and lead. The imbiber gets +1 Rad DR for the rest of the day after drinking it."
  },
  // { name: "1 Nuka-Cola Quartz", rarity: 5, source: "" },
  // { name: "1 Nuka-Cola Victory", rarity: 5, source: "" },
  {
    name: "Nuka-Cola Wild", 
    rarity: 2, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 2,
    otherEffects: "Gain 2 AP.",
    irradiated: 1,
    weight: 1,
    cost: 20,
    description: "The Nuka-Cola Corporation developed its Wild variant to compete with Sunset Sarsaparilla. While it never surpassed its competitor in the West, it was much more successful on the East Coast."
  },
  { 
    name: "Nuka-Cola Twist", 
    rarity: 4, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 2,
    otherEffects: "Gain 3 AP. See description.",
    irradiated: 1,
    weight: 1,
    cost: 25,
    description: "A \"mystery flavor\" variant released to promote Nuka-World, Nuka-Cola Twist is actually 6 different flavors with the same label. There's no way to distinguish which flavor it is until opened and tasted. Upon drinking, for the remainder of the day, reroll 1d20 on tests with a particular stat. Roll 1d6 to determine which stat is buffed. Drinking more Nuka-Cola Twist replaces the current bonus."
  },
  { 
    name: `Nuka-Cola ${(() => {
      const names = ["Vaccinated", "Scorched", "My Blood's In It"];
      names.sort(() => {
        const a = Math.random();
        const b = Math.random();
        if (a > b) return -1;
        if (a < b) return 1;
        return 0;
      });
      return names[0];
    })()}`, 
    rarity: 6, 
    source: "Homebrew", 
    type: "Beverages",
    hpHealed: 2,
    otherEffects: "+2 DR against all attacks from Scorched enemies.",
    irradiated: '-',
    weight: 1,
    cost: 20,
    description: "A special formula designed in Appalachia after the War. The formula was synthesized from a sample of a Vault Dweller's blood to distribute a vaccine against the Scorched Plague. Drinking one makes someone permanantly immune to Scorched Plague, in addition to temporary resistance to infected."
  },
];
export const chems = [
  { name: 'Addictol', rarity: 3, source: 'Core, 164' },
  { name: 'Antibiotics', rarity: 3, source: 'Core, 164' },
  { name: 'Berry Mentats', rarity: 3, source: 'Core, 164' },
  { name: 'Buffjet', rarity: 4, source: 'Core, 164' },
  { name: 'Buffout', rarity: 2, source: 'Core, 164' },
  { name: 'Bufftats', rarity: 4, source: 'Core, 164' },
  { name: 'Calmex', rarity: 4, source: 'Core, 164' },
  { name: 'Daddy-O', rarity: 2, source: 'Core, 164' },
  { name: 'Day Tripper', rarity: 3, source: 'Core, 165' },
  { name: 'Fury', rarity: 4, source: 'Core, 165' },
  { name: 'Grape Mentats', rarity: 3, source: 'Core, 165' },
  { name: 'Healing Salve', rarity: 1, source: 'Core, 165' },
  { name: 'Jet', rarity: 2, source: 'Core, 165' },
  { name: 'Jet Fuel', rarity: 3, source: 'Core, 165' },
  { name: 'Med-X', rarity: 2, source: 'Core, 165' },
  { name: 'Mentats', rarity: 2, source: 'Core, 165' },
  { name: 'Orange Mentats', rarity: 3, source: 'Core, 165' },
  { name: 'Overdrive', rarity: 3, source: 'Core, 165' },
  { name: 'Psycho', rarity: 2, source: 'Core, 165' },
  { name: 'Psycho Jet', rarity: 4, source: 'Core, 165' },
  { name: 'Psychobuff', rarity: 4, source: 'Core, 165' },
  { name: 'Psychotats', rarity: 4, source: 'Core, 165' },
  { name: 'Rad-X', rarity: 2, source: 'Core, 165' },
  { name: 'Rad-X (Diluted)', rarity: 1, source: 'Core, 165' },
  { name: 'RadAway', rarity: 2, source: 'Core, 165' },
  { name: 'RadAway (Diluted)', rarity: 1, source: 'Core, 165' },
  { name: 'Skeeto Spit', rarity: 2, source: 'Core, 165' },
  { name: 'Stimpak', rarity: 2, source: 'Core, 165' },
  { name: 'Stimpak (Diluted)', rarity: 1, source: 'Core, 165' },
  { name: 'Super Stimpak', rarity: 4, source: 'Core, 165' },
  // { name: 'Stimpak Diffuser', rarity: 5, source: 'Core, 165' },
  { name: 'Ultra Jet', rarity: 2, source: 'Core, 165' },
  { name: 'X-Cell', rarity: 4, source: 'Core, 165' },
];
export const forage = [
  { name: 'Brain Fungus', rarity: 1, source: 'Core, 149' },
  { name: 'Glowing Fungus', rarity: 1, source: 'Core, 149' },
  { name: 'Carrot', rarity: 1, source: 'Core, 149' },
  { name: 'Corn', rarity: 1, source: 'Core, 149' },
  { name: 'Gourd', rarity: 1, source: 'Core, 150' },
  { name: 'Melon', rarity: 1, source: 'Core, 150' },
  { name: 'Mutfruit', rarity: 0, source: 'Core, 150' },
  { name: 'Razorgrain', rarity: 1, source: 'Core, 151' },
  { name: 'Silt Bean', rarity: 1, source: 'Core, 151' },
  { name: 'Tato', rarity: 1, source: 'Core, 151' },
  { name: 'Hubflower', rarity: 1, source: '' },
  { name: 'Bloodleaf', rarity: 1, source: '' },
  { name: 'Honeycomb', rarity: 3, source: 'Wanderers, 114' },
  { name: 'Lure Weed', rarity: 1, source: 'Wanderers, 114' },
];
export const magazines = [
  { name: '¡La Fantoma!', rarity: 1, source: 'Core, 172' },
  { name: 'Astoundingly Awesome Tales', rarity: 1, source: 'Core, 172' },
  { name: 'Backwoodsman', rarity: 1, source: 'Core, 173' },
  { name: 'Boxing Times', rarity: 1, source: 'Core, 173' },
  { name: 'Duck and Cover!', rarity: 1, source: 'Core, 174' },
  { name: 'Fixing\' Things', rarity: 1, source: 'Core, 174' },
  { name: 'Future Weapons Today', rarity: 1, source: 'Core, 174' },
  { name: 'Grognak the Barbarian', rarity: 1, source: 'Core, 174' },
  { name: 'Guns and Bullets', rarity: 1, source: 'Core, 175' },
  { name: 'Live & Love', rarity: 1, source: 'Core, 176' },
  { name: 'Massachusetts Surgical Journal', rarity: 1, source: 'Core, 176' },
  { name: 'Meeting People', rarity: 1, source: 'Core, 176' },
  { name: 'Programmer\'s Digest', rarity: 1, source: 'Core, 176' },
  { name: 'Tales of a Junktown Jerky Vendor', rarity: 1, source: 'Core, 177' },
  { name: 'Tesla Science Magazine', rarity: 1, source: 'Core, 177' },
  { name: 'True Police Stories', rarity: 1, source: 'Core, 178' },
  { name: 'Tumblers Today', rarity: 1, source: 'Core, 178' },
  { name: 'Unstoppables', rarity: 1, source: 'Core, 178' },
  { name: 'U.S. Covert Operations Manual', rarity: 1, source: 'Core, 179' },
  { name: 'Wasteland Survival Guide', rarity: 1, source: 'Core, 180' },
  { name: '101 Heroic Last Stands', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Atomic Command (Holotape)', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Automatron (Holotape)', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Big Book of Science', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Chinese Army: Special Ops Training Manual', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Dress to Survive', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Duck and Cover Annual', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Grognak and the Ruby Ruins (Holotape)', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Guns and Bullets Annual', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Hot Summer Fashions', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Journal of Internal Medicine', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Nikola Tesla and You', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Pipfall (Holotape)', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Pugilism Illustrated', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Red Menace (Holotape)', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Scout Handbook', rarity: 5, source: 'Wanderers, 108' },
  { name: 'The Collected Adventures of Grognak the Barbarian', rarity: 5, source: 'Wanderers, 108' },
  { name: 'The Pointy End: A Guide to Swords', rarity: 5, source: 'Wanderers, 108' },
  { name: 'U.S. Army: 30 Handy Flamethrower Recipes', rarity: 5, source: 'Wanderers, 108' },
  { name: 'Zeta Invaders (Holotape)', rarity: 5, source: 'Wanderers, 108' },
];
export const nukaCola = [
  { name: "Empty", rarity: 0, source: "" },
  { name: "2CD + 1 glass bottles", rarity: 1, source: "" },
  { name: "1 Nuka-Cola", rarity: 2, source: "Core, 160" },  // HP 120, AP 30  - HP 2, AP 1
  { name: "2 Nuka-Cola", rarity: 3, source: "Core, 160" }, 
  { name: "1 Nuka-Cola, 1 Nuka-Cherry", rarity: 4, source: "Core, 160" },
  { name: "2 Nuka-Cola, 1 Nuka-Cherry", rarity: 5, source: "Core, 160" },
  { name: "1 Nuka-Cola Quantum", rarity: 6, source: "Core, 160" },  // HP 600, AP 300 - HP 10, AP 5
  { name: "1 Nuka-Cherry", rarity: 3, source: "Core, 160" }, // HP 300, AP 75 - HP 3, AP 2
  { name: "1 Nuka-Cola, 1 Nuka-Cherry, 1 Nuka Cola-Quantum", rarity: 8, source: "Core, 160" },
  // Other Variants (not in any book)
  { name: "1 Nuka-Cola Cranberry", rarity: 5, source: "Homebrew", type: "Beverage" },
  { name: "1 Nuka-Cola Dark", rarity: 5, source: "Homebrew", type: "Beverage" },
  { name: "1 Nuka-Grape", rarity: 5, source: "Homebrew", type: "Beverage" },
  { name: "1 Nuka-Cola Orange", rarity: 5, source: "Homebrew", type: "Beverage" },
  // { name: "1 Nuka-Cola Quartz", rarity: 5, source: "" },
  // { name: "1 Nuka-Cola Victory", rarity: 5, source: "" },
  { name: "1 Nuka-Cola Wild", rarity: 2.5, source: "Homebrew", type: "Beverage" },
  { name: "1 Nuka-Cola Twist", rarity: 4, source: "Homebrew", type: "Beverage" },
  { name: `1 Nuka-Cola ${(() => {
    const names = ["Vaccinated", "Scorched", "My Blood's In It"];
    names.sort(() => {
      const a = Math.random();
      const b = Math.random();
      if (a > b) return -1;
      if (a < b) return 1;
      return 0;
    });
    return names[0];
  })()}`, rarity: 6, source: "Homebrew", type: "Beverage" },
];
export const oddities = [
  { name: 'Robot Repait Kit', rarity: 2, source: 'Core, 170' },
  { name: 'Stealth Boy', rarity: 3, source: 'Core, 170' },
  { name: 'Stimpak Diffuser', rarity: 5, source: 'Core, 170' },
  { name: 'Behavioral Analysis Mod', rarity: 3, source: 'Core, 185' },
  { name: 'Diagnosis Mod', rarity: 3, source: 'Core, 185' },
  { name: 'Hacking Module', rarity: 2, source: 'Core, 185' },
  { name: 'Hazard Detection Mod', rarity: 2, source: 'Core, 185' },
  { name: 'Integral Boiler Mod', rarity: 1, source: 'Core, 185' },
  { name: 'Lockpick Module', rarity: 2, source: 'Core, 185' },
  { name: 'Radiation Coils', rarity: 3, source: 'Core, 185' },
  { name: 'Recon Sensors', rarity: 3, source: 'Core, 185' },
  { name: 'Regernation Field', rarity: 5, source: 'Core, 185' },
  { name: 'Resistance Field', rarity: 4, source: 'Core, 185' },
  { name: 'Sensor Array', rarity: 3, source: 'Core, 185' },
  { name: 'Stealth Field', rarity: 3, source: 'Core, 185' },
  { name: 'Tesla Coils', rarity: 5, source: 'Core, 185' },
  { name: 'Large Backpack', rarity: 2, source: 'Core, 181' },
  { name: 'Small Backpack', rarity: 1, source: 'Core, 181' },
  { name: 'Deluxe Toolkit', rarity: 3, source: 'Core, 181' },
  { name: 'Doctor\'s Bag', rarity: 3, source: 'Core, 181' },
  { name: 'Electronic Lockpicker', rarity: 4, source: 'Core, 181' },
  { name: 'First Aid Kit', rarity: 2, source: 'Core, 181' },
  { name: 'Flashlight', rarity: 3, source: 'Core, 181' },
  { name: 'Geiger Counter', rarity: 3, source: 'Core, 181' },
  { name: 'Holotags', rarity: 2, source: 'Core, 181' },
  { name: 'Holotape Player', rarity: 2, source: 'Core, 181' },
  { name: 'Lantern', rarity: 2, source: 'Core, 181' },
  { name: 'Lock Pick Set', rarity: 2, source: 'Core, 181' },
  { name: 'Multi-Tool', rarity: 2, source: 'Core, 181' },
  // { name: 'Pack Brahmin', rarity: 3, source: 'Core, 181' },
  { name: 'Radio', rarity: 2, source: 'Core, 181' },
  { name: 'Signal Flare', rarity: 1, source: 'Core, 181' },
  { name: 'Torch', rarity: 1, source: 'Core, 181' },
  // Other
  { name: "Pre-War Money Worth 5d20 Caps", rarity: 5, source: '' },
  { name: "Pre-War Money Worth 4d20 Caps", rarity: 4, source: '' },
  { name: "Pre-War Money Worth 3d20 Caps", rarity: 3, source: '' },
  { name: "5d20 Caps", rarity: 4, source: '' },
  { name: "4d20 Caps", rarity: 3, source: '' },
  { name: "3d20 Caps", rarity: 2, source: '' },
  { name: "2d20 Caps", rarity: 1, source: '' },
  { name: "1d20 Caps", rarity: 0, source: '' },
  { name: '2CD + 1 Bobby Pins', rarity: 0, source: 'Core, 181' },
  { name: '4CD + 2 Bobby Pins', rarity: 1, source: 'Core, 181' },
  { name: '6CD + 3 Bobby Pins', rarity: 2, source: 'Core, 181' },
  { name: '8CD + 4 Bobby Pins', rarity: 3, source: 'Core, 181' },
  { name: '10CD + 5 Bobby Pins', rarity: 4, source: 'Core, 181' },
  { name: 'Key', rarity: 4, source: '' },
  { name: 'Container', rarity: 2, source: '' },
  { name: 'Magazine', rarity: 3, source: '' },
  { name: 'Locked Container', rarity: 4, source: '' },
];

export const legendaryBaseItems = [
  { name: '.44 Pistol', rarity: 2, source: 'Core, 95' },
  { name: '10mm Pistol', rarity: 1, source: 'Core, 95' },
  { name: 'Flare Gun', rarity: 1, source: 'Core, 95' },
  { name: 'Assault Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Combat Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Gauss Rifle', rarity: 4, source: 'Core, 95' },
  { name: 'Hunting Rifle', rarity: 2, source: 'Core, 95' },
  { name: 'Submachine Gun', rarity: 1, source: 'Core, 95' },
  { name: 'Combat Shotgun', rarity: 2, source: 'Core, 95' },
  { name: 'Double-Barrel Shotgun', rarity: 1, source: 'Core, 95' },
  { name: 'Pipe Bolt-Action', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Gun', rarity: 0, source: 'Core, 95' },
  { name: 'Pipe Revolver', rarity: 0, source: 'Core, 95' },
  { name: 'Railway Rifle', rarity: 4, source: 'Core, 95' },
  { name: 'Syringer', rarity: 2, source: 'Core, 95' },
  { name: 'M79 Grenade Launcher', rarity: 3, source: 'Settlers, 90' },
  { name: '.357 Magnum Revolver', rarity: 2, source: 'Wanderers, 60' },
  { name: '12.7mm Pistol', rarity: 4, source: 'Wanderers, 60' },
  { name: '12.7mm SMG', rarity: 4, source: 'Wanderers, 60' },
  { name: '25mm Grenade APW', rarity: 4, source: 'Wanderers, 60' },
  { name: '9mm Pistol', rarity: 2, source: 'Wanderers, 60' },
  { name: 'Anti-Materiel Rifle', rarity: 4, source: 'Wanderers, 60' },
  { name: 'Battle Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Blunderbuss', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Pistol', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Black Powder Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Gauss Pistol', rarity: 5, source: 'Wanderers, 60' },
  { name: 'Gauss Shotgun', rarity: 5, source: 'Wanderers, 60' },
  { name: 'Lever-Action Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Light Machine Gun', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Pump-Action Shotgun', rarity: 1, source: 'Wanderers, 60' },
  { name: 'Radium Rifle', rarity: 3, source: 'Wanderers, 60' },
  { name: 'Sniper Rifle', rarity: 4, source: 'Wanderers, 60' },
  { name: 'Institute Laser', rarity: 2, source: 'Core, 101' },
  { name: 'Laser Musket', rarity: 1, source: 'Core, 101' },
  { name: 'Laser Gun', rarity: 2, source: 'Core, 101' },
  { name: 'Plasma Gun', rarity: 3, source: 'Core, 101' },
  { name: 'Gamma Gun', rarity: 5, source: 'Core, 101' },
  { name: 'Acid Soaker', rarity: 3, source: 'Settlers, 91' },
  { name: 'Alien Blaster', rarity: 5, source: 'Settlers, 91' },
  // { name: 'Assaultron Head Laser', rarity: 4, source: 'Settlers, 91' },
  { name: 'Assaultron Head', rarity: 3, source: 'Wanderers, 65' },
  { name: 'Mesmetron', rarity: 4, source: 'Settlers, 91' },
  { name: 'Alien Atomizer', rarity: 5, source: 'Wanderers, 65' },
  { name: 'Alien Disintegrator', rarity: 5, source: 'Wanderers, 65' },
  { name: 'Arc Welder', rarity: 4, source: 'Wanderers, 65' },
  { name: 'Microwave Emitter', rarity: 5, source: 'Wanderers, 65' },
  // { name: 'Tesla Rifle', rarity: 4, source: 'Settlers, 91' },
  { name: 'Tesla Rifle', rarity: 4, source: 'Wanderers, 65' },
  { name: 'Fat Man', rarity: 4, source: 'Core, 106' },
  { name: 'Flamer', rarity: 3, source: 'Core, 106' },
  { name: 'Gatling Laser', rarity: 3, source: 'Core, 106' },
  { name: 'Heavy Incinerator', rarity: 4, source: 'Core, 106' },
  { name: 'Junk Jet', rarity: 3, source: 'Core, 106' },
  { name: 'Minigun', rarity: 2, source: 'Core, 106' },
  { name: 'Missile Launcher', rarity: 4, source: 'Core, 106' },
  { name: 'Broadsider', rarity: 5, source: 'Settlers, 94' },
  { name: 'Cryolator', rarity: 4, source: 'Settlers, 94' },
  { name: 'Harpoon Gun', rarity: 5, source: 'Settlers, 94' },
  { name: '.50 Cal Machine Gun', rarity: 3, source: 'Wanderers, 67' },
  { name: 'Auto Grenade Launcher', rarity: 4, source: 'Wanderers, 67' },
  { name: 'Drone Cannon', rarity: 5, source: 'Wanderers, 67' },
  { name: 'Gatling Gun', rarity: 1, source: 'Wanderers, 67' },
  { name: 'Gatling Plasma', rarity: 4, source: 'Wanderers, 67' },
  { name: 'Gauss Minigun', rarity: 6, source: 'Wanderers, 67' },
  { name: 'Plasma Caster', rarity: 5, source: 'Wanderers, 67' },
  { name: 'Tesla Cannon', rarity: 5, source: 'Wanderers, 67' },
  { name: 'Bow', rarity: 1, source: 'Wanderers, 73' },
  { name: 'Crossbow', rarity: 2, source: 'Wanderers, 73' },
  { name: 'Sword', rarity: 2, source: 'Core, 111' },
  { name: 'Combat Knife', rarity: 1, source: 'Core, 111' },
  { name: 'Machete', rarity: 1, source: 'Core, 111' },
  { name: 'Ripper', rarity: 2, source: 'Core, 111' },
  { name: 'Shishkebab', rarity: 3, source: 'Core, 111' },
  { name: 'Switchblade', rarity: 0, source: 'Core, 111' },
  { name: 'Baseball Bat', rarity: 1, source: 'Core, 111' },
  { name: 'Aluminum Baseball Bat', rarity: 2, source: 'Core, 111' },
  { name: 'Board', rarity: 0, source: 'Core, 111' },
  { name: 'Lead Pipe', rarity: 0, source: 'Core, 111' },
  { name: 'Pipe Wrench', rarity: 1, source: 'Core, 111' },
  { name: 'Pool Cue', rarity: 0, source: 'Core, 111' },
  { name: 'Rolling Pin', rarity: 0, source: 'Core, 111' },
  { name: 'Baton', rarity: 1, source: 'Core, 111' },
  { name: 'Sledgehammer', rarity: 2, source: 'Core, 111' },
  { name: 'Super Sledge', rarity: 3, source: 'Core, 111' },
  { name: 'Tire Iron', rarity: 1, source: 'Core, 111' },
  { name: 'Walking Cane', rarity: 0, source: 'Core, 111' },
  { name: 'Boxing Glove', rarity: 1, source: 'Core, 111' },
  { name: 'Deathclaw Gauntlet', rarity: 3, source: 'Core, 111' },
  { name: 'Knuckles', rarity: 1, source: 'Core, 111' },
  { name: 'Power Fist', rarity: 2, source: 'Core, 111' },
  { name: 'Assaultron Blade', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Auto-Axe', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Ballistic Fist', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Bumper Sword', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Cattle Prod', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Chainsaw', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Death Tambo', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Displacer Glove', rarity: 4, source: 'Wanderers, 75' },
  { name: 'Guitar Sword', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Mr Handy Buzz Blade', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Multi-Purpose Axe', rarity: 2, source: 'Wanderers, 75' },
  { name: 'Proton Axe', rarity: 5, source: 'Wanderers, 75' },
  { name: 'War Drum', rarity: 3, source: 'Wanderers, 75' },
  { name: 'Raider Armor Piece (Standard)', rarity: 0, source: 'Core, 130' },
  { name: 'Raider Armor Piece (Sturdy)', rarity: 1, source: 'Core, 130' },
  { name: 'Raider Armor Piece (Heavy)', rarity: 2, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Standard)', rarity: 1, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Sturdy)', rarity: 2, source: 'Core, 130' },
  { name: 'Leather Armor Piece (Heavy)', rarity: 3, source: 'Core, 130' },
  { name: 'Metal Armor Piece (Standard)', rarity: 1, source: 'Core, 131' },
  { name: 'Metal Armor Piece (Sturdy)', rarity: 2, source: 'Core, 131' },
  { name: 'Metal Armor Piece (Heavy)', rarity: 3, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Standard)', rarity: 2, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Sturdy)', rarity: 3, source: 'Core, 131' },
  { name: 'Combat Armor Piece (Heavy)', rarity: 4, source: 'Core, 131' },
  { name: 'Synth Armor Piece (Standard)', rarity: 3, source: 'Core, 132' },
  { name: 'Synth Armor Piece (Sturdy)', rarity: 4, source: 'Core, 132' },
  { name: 'Synth Armor Piece (Heavy)', rarity: 5, source: 'Core, 132' },
  { name: 'Legionary Armor Piece (Recruit)', rarity: 3, source: 'Wanderers, 89' },
  { name: 'Legionary Armor Piece', rarity: 4, source: 'Wanderers, 89' },
  { name: 'Legionary Armor Piece (Centurion)', rarity: 5, source: 'Wanderers, 89' },
  { name: 'Marine Armor Piece', rarity: 4, source: 'Wanderers, 90' },
  { name: 'Scout Armor Piece', rarity: 4, source: 'Wanderers, 91' },
  { name: 'Robot Armor Piece (Standard)', rarity: 2, source: 'Wanderers, 92' },
  { name: 'Robot Armor Piece (Sturdy)', rarity: 3, source: 'Wanderers, 92' },
  { name: 'Robot Armor Piece (Heavy)', rarity: 4, source: 'Wanderers, 92' },
  { name: 'Wood Armor Piece', rarity: 0, source: 'Wanderers, 93' },
  { name: 'Raider Power Armor Piece', rarity: 2, source: 'Core, 137' },
  { name: 'T-45 Power Armor Piece', rarity: 2, source: 'Core, 137' },
  { name: 'T-51 Power Armor Piece', rarity: 3, source: 'Core, 137' },
  { name: 'T-60 Power Armor Piece', rarity: 4, source: 'Core, 137' },
  { name: 'X-01 Power Armor Piece', rarity: 5, source: 'Core, 137' },
  { name: 'Excavator Power Armor Piece', rarity: 3, source: 'Wanderers, 94' },
  { name: 'Hellcat Power Armor Piece', rarity: 3, source: 'Wanderers, 95' },
  { name: 'T-65 Power Armor Piece', rarity: 5, source: 'Wanderers, 89' },
];